-- ================================================
-- 공통코드 초기 데이터 (TB_CODE)
-- 코드체계: CD + 4자리 [대분류][중분류][소분류][예비]
--   L0 ROOT       : CD0000
--   L1 대분류     : CD1000 소득 / CD2000 비용 / CD3000 기관분류 / CD4000 투자
--   L2 중분류     : CDx100, CDx200 ...
--   L3 소분류     : CDxy10, CDxy20 ...
-- ================================================

-- L0 ROOT
INSERT IGNORE INTO tb_code (CD_ID, CD_NM, CD_LEVEL, PARENT_CD_ID, SORT_ORDER, DEL_YN)
VALUES ('CD0000', 'ROOT', 0, NULL, 0, 'N');

-- ── L1 대분류 ──────────────────────────────────
INSERT IGNORE INTO tb_code (CD_ID, CD_NM, CD_LEVEL, PARENT_CD_ID, SORT_ORDER, DEL_YN) VALUES ('CD1000', '소득',     1, 'CD0000', 1, 'N');
INSERT IGNORE INTO tb_code (CD_ID, CD_NM, CD_LEVEL, PARENT_CD_ID, SORT_ORDER, DEL_YN) VALUES ('CD2000', '비용',     1, 'CD0000', 2, 'N');
INSERT IGNORE INTO tb_code (CD_ID, CD_NM, CD_LEVEL, PARENT_CD_ID, SORT_ORDER, DEL_YN) VALUES ('CD3000', '기관분류', 1, 'CD0000', 3, 'N');
INSERT IGNORE INTO tb_code (CD_ID, CD_NM, CD_LEVEL, PARENT_CD_ID, SORT_ORDER, DEL_YN) VALUES ('CD4000', '투자',     1, 'CD0000', 4, 'N');

-- ── 소득 (CD1000) L2 ──────────────────────────
INSERT IGNORE INTO tb_code (CD_ID, CD_NM, CD_LEVEL, PARENT_CD_ID, SORT_ORDER, DEL_YN) VALUES ('CD1100', '급여',     2, 'CD1000', 1, 'N');
INSERT IGNORE INTO tb_code (CD_ID, CD_NM, CD_LEVEL, PARENT_CD_ID, SORT_ORDER, DEL_YN) VALUES ('CD1200', '이자소득', 2, 'CD1000', 2, 'N');
INSERT IGNORE INTO tb_code (CD_ID, CD_NM, CD_LEVEL, PARENT_CD_ID, SORT_ORDER, DEL_YN) VALUES ('CD1300', '배당소득', 2, 'CD1000', 3, 'N');

-- ── 비용 (CD2000) L2 ──────────────────────────
INSERT IGNORE INTO tb_code (CD_ID, CD_NM, CD_LEVEL, PARENT_CD_ID, SORT_ORDER, DEL_YN) VALUES ('CD2100', '고정비용', 2, 'CD2000', 1, 'N');
INSERT IGNORE INTO tb_code (CD_ID, CD_NM, CD_LEVEL, PARENT_CD_ID, SORT_ORDER, DEL_YN) VALUES ('CD2200', '가변비용', 2, 'CD2000', 2, 'N');

-- 고정비용 (CD2100) L3
INSERT IGNORE INTO tb_code (CD_ID, CD_NM, CD_LEVEL, PARENT_CD_ID, SORT_ORDER, DEL_YN) VALUES ('CD2110', '통신비',     3, 'CD2100', 1, 'N');
INSERT IGNORE INTO tb_code (CD_ID, CD_NM, CD_LEVEL, PARENT_CD_ID, SORT_ORDER, DEL_YN) VALUES ('CD2120', '관리비/세금', 3, 'CD2100', 2, 'N');
INSERT IGNORE INTO tb_code (CD_ID, CD_NM, CD_LEVEL, PARENT_CD_ID, SORT_ORDER, DEL_YN) VALUES ('CD2130', '보험비',     3, 'CD2100', 3, 'N');
INSERT IGNORE INTO tb_code (CD_ID, CD_NM, CD_LEVEL, PARENT_CD_ID, SORT_ORDER, DEL_YN) VALUES ('CD2140', '정기구독',   3, 'CD2100', 4, 'N');

-- 가변비용 (CD2200) L3
INSERT IGNORE INTO tb_code (CD_ID, CD_NM, CD_LEVEL, PARENT_CD_ID, SORT_ORDER, DEL_YN) VALUES ('CD2210', '카드값', 3, 'CD2200', 1, 'N');
INSERT IGNORE INTO tb_code (CD_ID, CD_NM, CD_LEVEL, PARENT_CD_ID, SORT_ORDER, DEL_YN) VALUES ('CD2220', '기타',   3, 'CD2200', 2, 'N');

-- ── 기관분류 (CD3000) L2 ──────────────────────
INSERT IGNORE INTO tb_code (CD_ID, CD_NM, CD_LEVEL, PARENT_CD_ID, SORT_ORDER, DEL_YN) VALUES ('CD3100', '카드사', 2, 'CD3000', 1, 'N');
INSERT IGNORE INTO tb_code (CD_ID, CD_NM, CD_LEVEL, PARENT_CD_ID, SORT_ORDER, DEL_YN) VALUES ('CD3200', '보험사', 2, 'CD3000', 2, 'N');
INSERT IGNORE INTO tb_code (CD_ID, CD_NM, CD_LEVEL, PARENT_CD_ID, SORT_ORDER, DEL_YN) VALUES ('CD3300', '은행',   2, 'CD3000', 3, 'N');
INSERT IGNORE INTO tb_code (CD_ID, CD_NM, CD_LEVEL, PARENT_CD_ID, SORT_ORDER, DEL_YN) VALUES ('CD3400', '증권사', 2, 'CD3000', 4, 'N');

-- 카드사 (CD3100) L3
INSERT IGNORE INTO tb_code (CD_ID, CD_NM, CD_LEVEL, PARENT_CD_ID, SORT_ORDER, DEL_YN) VALUES ('CD3110', '삼성카드', 3, 'CD3100', 1, 'N');
INSERT IGNORE INTO tb_code (CD_ID, CD_NM, CD_LEVEL, PARENT_CD_ID, SORT_ORDER, DEL_YN) VALUES ('CD3120', '신한카드', 3, 'CD3100', 2, 'N');
INSERT IGNORE INTO tb_code (CD_ID, CD_NM, CD_LEVEL, PARENT_CD_ID, SORT_ORDER, DEL_YN) VALUES ('CD3130', '현대카드', 3, 'CD3100', 3, 'N');
INSERT IGNORE INTO tb_code (CD_ID, CD_NM, CD_LEVEL, PARENT_CD_ID, SORT_ORDER, DEL_YN) VALUES ('CD3140', '국민카드', 3, 'CD3100', 4, 'N');
INSERT IGNORE INTO tb_code (CD_ID, CD_NM, CD_LEVEL, PARENT_CD_ID, SORT_ORDER, DEL_YN) VALUES ('CD3150', '비씨카드', 3, 'CD3100', 5, 'N');
INSERT IGNORE INTO tb_code (CD_ID, CD_NM, CD_LEVEL, PARENT_CD_ID, SORT_ORDER, DEL_YN) VALUES ('CD3160', '하나카드', 3, 'CD3100', 6, 'N');

-- 보험사 (CD3200) L3
INSERT IGNORE INTO tb_code (CD_ID, CD_NM, CD_LEVEL, PARENT_CD_ID, SORT_ORDER, DEL_YN) VALUES ('CD3210', '삼성화재',   3, 'CD3200', 1, 'N');
INSERT IGNORE INTO tb_code (CD_ID, CD_NM, CD_LEVEL, PARENT_CD_ID, SORT_ORDER, DEL_YN) VALUES ('CD3220', '현대해상',   3, 'CD3200', 2, 'N');
INSERT IGNORE INTO tb_code (CD_ID, CD_NM, CD_LEVEL, PARENT_CD_ID, SORT_ORDER, DEL_YN) VALUES ('CD3230', '동양생명',   3, 'CD3200', 3, 'N');
INSERT IGNORE INTO tb_code (CD_ID, CD_NM, CD_LEVEL, PARENT_CD_ID, SORT_ORDER, DEL_YN) VALUES ('CD3240', 'DB손해보험', 3, 'CD3200', 4, 'N');

-- 은행 (CD3300) L3
INSERT IGNORE INTO tb_code (CD_ID, CD_NM, CD_LEVEL, PARENT_CD_ID, SORT_ORDER, DEL_YN) VALUES ('CD3310', '우리은행',       3, 'CD3300', 1, 'N');
INSERT IGNORE INTO tb_code (CD_ID, CD_NM, CD_LEVEL, PARENT_CD_ID, SORT_ORDER, DEL_YN) VALUES ('CD3320', '신한은행',       3, 'CD3300', 2, 'N');
INSERT IGNORE INTO tb_code (CD_ID, CD_NM, CD_LEVEL, PARENT_CD_ID, SORT_ORDER, DEL_YN) VALUES ('CD3330', '오케이저축은행', 3, 'CD3300', 3, 'N');
INSERT IGNORE INTO tb_code (CD_ID, CD_NM, CD_LEVEL, PARENT_CD_ID, SORT_ORDER, DEL_YN) VALUES ('CD3340', '대신저축은행',   3, 'CD3300', 4, 'N');
INSERT IGNORE INTO tb_code (CD_ID, CD_NM, CD_LEVEL, PARENT_CD_ID, SORT_ORDER, DEL_YN) VALUES ('CD3350', '새마을금고',     3, 'CD3300', 5, 'N');

-- 증권사 (CD3400) L3
INSERT IGNORE INTO tb_code (CD_ID, CD_NM, CD_LEVEL, PARENT_CD_ID, SORT_ORDER, DEL_YN) VALUES ('CD3410', '미래에셋', 3, 'CD3400', 1, 'N');
INSERT IGNORE INTO tb_code (CD_ID, CD_NM, CD_LEVEL, PARENT_CD_ID, SORT_ORDER, DEL_YN) VALUES ('CD3420', '토스',     3, 'CD3400', 2, 'N');

-- ── 투자 (CD4000) L2 ──────────────────────────
INSERT IGNORE INTO tb_code (CD_ID, CD_NM, CD_LEVEL, PARENT_CD_ID, SORT_ORDER, DEL_YN) VALUES ('CD4100', '배당투자', 2, 'CD4000', 1, 'N');
INSERT IGNORE INTO tb_code (CD_ID, CD_NM, CD_LEVEL, PARENT_CD_ID, SORT_ORDER, DEL_YN) VALUES ('CD4200', '퇴직연금', 2, 'CD4000', 2, 'N');
